/**
 * Write the repo-root `.env`, with the secrets already generated.
 *
 * The alternative is a README telling somebody to run `openssl rand -hex 32`
 * three times and paste the results into the right lines, which is how a deploy
 * ends up with `AUTH_SECRET=change-me` — the failure env.ts already refuses to
 * boot on. Generating them is strictly less work than documenting how to.
 *
 *   bun run env:gen           # write the file, refusing to clobber an existing one
 *   bun run env:gen --force   # overwrite, keeping a .bak
 *
 * ponytail: string templating, not a dotenv library. This writes one file once.
 */

import { randomBytes } from "node:crypto";
import { copyFileSync, existsSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const TARGET = join(import.meta.dir, "..", ".env");
const force = process.argv.includes("--force");

const secret = () => randomBytes(32).toString("hex");

const file = `# Generated by \`bun run env:gen\` — safe to edit by hand.
# Secrets below are unique to this machine. Never commit this file.
# Every variable the system reads is documented in .env.example.

# Where the browser is. Every magic link is built against this, so a wrong value
# mails out links that 404.
WEB_ORIGIN=http://localhost:3000

# The API is a second port in development and the frontend dev server does not
# proxy /api, so a magic link built against WEB_ORIGIN would land on the SPA and
# silently sign nobody in.
API_ORIGIN=http://localhost:3001

# ─── Secrets ──────────────────────────────────────────────────────────────────
# Signs the voter identity cookie and the network hashes. Rotating it resets
# every voter's identity, so treat it as permanent.
VOTE_SECRET=${secret()}

# Signs the sign-in session cookie (HS256, via jose). Separate from VOTE_SECRET
# on purpose: this one can be rotated to log everybody out without also throwing
# away every vote's identity. Unset disables sign-in entirely.
AUTH_SECRET=${secret()}

# Required for /api/admin/*.
ADMIN_TOKEN=${secret()}

# Comma-separated emails that are platform operators when signed in as
# themselves. Nothing to generate: fill in your own address.
SITE_ADMIN=

# ─── Sign-in ──────────────────────────────────────────────────────────────────
MAGIC_LINK_TTL_MS=900000
SESSION_TTL_MS=2592000000
# Sign-in links per email address per hour.
MAGIC_LINKS_PER_HOUR=3

# ─── Mail ─────────────────────────────────────────────────────────────────────
# MAIL_DEV_SINK=true redirects ALL mail to the local mailpit, ignoring the SMTP_*
# settings below — so the real credentials can stay here while you test. Opt-in,
# and IGNORED when NODE_ENV=production, so it can never silently swallow a
# sign-in link on a live box.
# MAIL_DEV_SINK=true

# Local dev goes to mailpit, which \`bun run dev\` starts for you. It accepts
# anything, delivers nothing, and shows every message at http://localhost:8025 —
# so the sign-in link and the "send us your creative" mail are both readable as
# the recipient actually sees them, not as a line in a log.
#
# Only SMTP_HOST is required; mailpit needs no credentials.
SMTP_HOST=localhost
SMTP_PORT=1025
MAIL_FROM=canireplaceit <hello@canireplaceit.local>

# For Gmail instead: SMTP_PASS must be a 16-character App Password (Google
# account → Security → App passwords), never the account password, and the
# account needs 2FA on for that menu to exist. MAIL_FROM must match SMTP_USER or
# Gmail rewrites it.
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=465
# SMTP_USER=canireplaceit@gmail.com
# SMTP_PASS=
# MAIL_FROM=canireplaceit <canireplaceit@gmail.com>

# ─── Demo data ────────────────────────────────────────────────────────────────
# Fills an empty database on boot with live sponsors, orders mid-funnel, and
# enough ad traffic for the rate card to clear its reporting threshold.
#
# IGNORED when NODE_ENV=production, whatever this says: seeded rows include live
# placements nobody paid for. \`bun run dev:rm\` wipes and starts over.
SEED_DEV=true

# ─── Analytics (self-hosted Umami) ────────────────────────────────────────────
# All four are required together — a URL with no credentials reads nothing, so
# half-configured means OFF rather than a stream of 401s.
#
# Self-hosted Umami has NO api keys (that is Umami Cloud): it issues a bearer
# token from username+password. Use a VIEW-ONLY user, so this credential grants
# nothing worth stealing.
#
# UMAMI_WEBSITE_ID is the uuid from Umami → Websites → (the site) → Edit. The
# account above must have access to it, or every read 401s. Check with:
#   curl -H "Authorization: Bearer <admin token>" $UMAMI_URL/api/admin/site/stats/diag
# UMAMI_URL=https://umami.example.com
# UMAMI_WEBSITE_ID=
# UMAMI_USERNAME=
# UMAMI_PASSWORD=
UMAMI_STATS_TTL_MS=300000
UMAMI_STATS_WINDOW_DAYS=30
UMAMI_TIMEOUT_MS=8000

# ─── Payments ─────────────────────────────────────────────────────────────────
# unset = no checkout at all (503). \`fake\` completes purchases WITHOUT CHARGING
# ANYONE, and is IGNORED when NODE_ENV=production — so the local demo can run the
# whole funnel (reserve → pay → creative email → approve → live) with no Stripe
# account. Every purchase it settles is stamped provider="fake-dev" on the row,
# so a database that ran it can never be mistaken for one that took real money.
PAYMENTS_PROVIDER=fake

# Optional invisible human check on votes.
TURNSTILE_SECRET=

# Nightly regeneration of the static site. Off in dev, where it is just noise.
REBUILD_ENABLED=false
REBUILD_INTERVAL_MS=86400000

# ─── Logging ──────────────────────────────────────────────────────────────────
# pino level. Defaults to "debug" in development, "info" in production.
# LOG_LEVEL=info
`;

if (existsSync(TARGET) && !force) {
	console.error(
		`refusing to overwrite ${TARGET}\n` +
			`It already exists, and regenerating it would mint new secrets — which logs\n` +
			`out every session and invalidates every voter identity. Pass --force if that\n` +
			`is what you want (the old file is kept as .env.bak).`,
	);
	process.exit(1);
}

if (existsSync(TARGET)) copyFileSync(TARGET, `${TARGET}.bak`);
writeFileSync(TARGET, file, { mode: 0o600 });

console.log(
	`wrote ${TARGET}\n` +
		`  VOTE_SECRET, AUTH_SECRET, ADMIN_TOKEN generated (32 random bytes each)\n` +
		`  mail goes to the local mailpit — read it at http://localhost:8025\n` +
		`  next: bun run dev`,
);
