#!/usr/bin/env bun
/**
 * Validates everything under data/. Run locally with `bun run validate`;
 * CI runs the same thing on every pull request.
 */

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { basename, join } from "node:path";
import {
	type Category,
	type HealthFile,
	healthKey,
	type Issue,
	isArchived,
	type Product,
	productLangs,
	validateCategory,
	validateProduct,
} from "core/src/content";
import { SupportedLangs } from "core/src/index";

const ROOT = join(import.meta.dir, "..");
const DATA = join(ROOT, "data");

let failed = 0;
const report = (file: string, issues: Issue[]) => {
	if (issues.length === 0) return;
	failed += issues.length;
	console.error(`\n✗ ${file}`);
	for (const i of issues) console.error(`    ${i.path}: ${i.message}`);
};

const readJson = (path: string): unknown => {
	try {
		return JSON.parse(readFileSync(path, "utf8"));
	} catch (e) {
		report(path, [
			{ path: ".", message: `invalid JSON — ${(e as Error).message}` },
		]);
		return null;
	}
};

// ---- categories ----
const categories = readJson(join(DATA, "categories.json")) as Category[] | null;
if (!Array.isArray(categories)) {
	console.error("✗ data/categories.json must be an array");
	process.exit(1);
}
categories.forEach((c, i) => {
	report("data/categories.json", validateCategory(c, i));
});

const slugs = new Set(categories.map((c) => c.slug));
if (slugs.size !== categories.length) {
	report("data/categories.json", [
		{ path: ".", message: "duplicate category slugs" },
	]);
}

// ---- products ----
const dir = join(DATA, "products");
const files = readdirSync(dir).filter((f) => f.endsWith(".json"));
const seen = new Set<string>();
const products: Product[] = [];

for (const file of files) {
	const value = readJson(join(dir, file));
	if (value === null) continue;
	const name = basename(file, ".json");
	const issues = validateProduct(value, name, slugs);
	if (seen.has(name))
		issues.push({ path: "slug", message: "duplicate product" });
	seen.add(name);
	report(`data/products/${file}`, issues);
	if (issues.length === 0) products.push(value as Product);
}

/* ---- archived repos -------------------------------------------------------
 *
 * `data/health.json` is generated by `bun run health` (weekly, via
 * .github/workflows/health.yml) and committed. Validation only ever reads the
 * one field that is a hard, forge-reported fact rather than a judgement:
 * `archived`.
 *
 * ONLY A POSITIVE `archived: true` IS COUNTED. A repo with no entry in the
 * file, or an entry with no `archived` key, is simply not archived as far as
 * this pass is concerned — and that is not a loophole, it is the only correct
 * behaviour:
 *
 *   - a brand new PR's repo has never been swept, so it cannot be in the file;
 *   - GitLab's unauthenticated API does not report `archived` at all, and
 *     Savannah is not queried, so those readings legitimately omit it;
 *   - a fresh clone that has never run `bun run health` has no file.
 *
 * Absence is not evidence, in either direction: it is neither proof a project
 * is alive nor proof it is dead, so it is reported as neither.
 *
 * It is REPORTED AND COUNTED, not an error. It used to fail the build, on the
 * reasoning that a dead repo cited as a live alternative is a lie. That was the
 * wrong fix for a real problem: it made the catalogue silently forget every
 * project that ever died, so "does a replacement exist?" and "did one ever
 * exist?" collapsed into the same answer. Buttercup and grafana/oncall are part
 * of the record precisely BECAUSE they stopped.
 *
 * The honesty problem is solved where it belongs — in the UI, which already
 * renders an Archived badge off this same `archived` flag (see RepoBadges in
 * apps/frontend/src/components.tsx). A reader sees the project and sees that it
 * is done. Nothing is hidden and nothing is claimed.
 */
const healthPath = join(DATA, "health.json");
const archived: string[] = [];
{
	// Health covers about a third of the cited repos, so reading it alone found
	// 11 of the ~190 dead projects in here and reported the rest as fine. The
	// entry's own `archived` carries the other two-thirds; the forge still wins
	// where it has an opinion. Same rule as `isArchived` in core.
	const health = existsSync(healthPath)
		? (readJson(healthPath) as HealthFile | null)
		: null;
	const repos = health?.repos ?? {};
	for (const p of products) {
		for (const a of p.alternatives) {
			if (a.kind !== "oss") continue;
			if (!isArchived(a, repos[healthKey(a.source)])) continue;
			archived.push(`${p.slug} → ${a.name} (${a.source.path})`);
		}
	}
}

// ---- summary ----
const byVerdict = (v: string) => products.filter((p) => p.verdict === v).length;
const altCount = products.reduce((n, p) => n + p.alternatives.length, 0);
const cheaper = products.filter((p) =>
	p.alternatives.some((a) => a.kind === "cheaper"),
).length;

console.log(
	`\n${files.length} products · ${categories.length} categories · ${altCount} alternatives`,
);
console.log(
	`  verdicts: ${byVerdict("yes")} replaceable, ${byVerdict("almost")} almost, ${byVerdict("not-yet")} not yet`,
);
console.log(`  ${cheaper} products also list a cheaper commercial option`);
// Kept and shown, not dropped — the catalogue records what existed too.
if (archived.length > 0) {
	console.log(
		`  ${archived.length} alternatives archived upstream, shown with a badge:`,
	);
	for (const a of archived) console.log(`    ${a}`);
}
for (const lang of SupportedLangs) {
	const n = products.filter((p) => productLangs(p).includes(lang)).length;
	const pct = files.length ? Math.round((n / files.length) * 100) : 0;
	console.log(`  ${lang}: ${n}/${files.length} fully translated (${pct}%)`);
}

if (failed > 0) {
	console.error(`\n${failed} problem(s). Nothing was written.`);
	process.exit(1);
}
console.log("\nAll good.");
