#!/usr/bin/env bun
/**
 * Validates everything under data/. Run locally with `bun run validate`;
 * CI runs the same thing on every pull request.
 */

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { basename, join } from "node:path";
import {
	type Category,
	type HealthFile,
	healthKey,
	type Issue,
	type Product,
	productLangs,
	validateCategory,
	validateProduct,
} from "core/src/content";
import { SupportedLangs } from "core/src/index";

const ROOT = join(import.meta.dir, "..");
const DATA = join(ROOT, "data");

let failed = 0;
const report = (file: string, issues: Issue[]) => {
	if (issues.length === 0) return;
	failed += issues.length;
	console.error(`\n✗ ${file}`);
	for (const i of issues) console.error(`    ${i.path}: ${i.message}`);
};

const readJson = (path: string): unknown => {
	try {
		return JSON.parse(readFileSync(path, "utf8"));
	} catch (e) {
		report(path, [
			{ path: ".", message: `invalid JSON — ${(e as Error).message}` },
		]);
		return null;
	}
};

// ---- categories ----
const categories = readJson(join(DATA, "categories.json")) as Category[] | null;
if (!Array.isArray(categories)) {
	console.error("✗ data/categories.json must be an array");
	process.exit(1);
}
categories.forEach((c, i) => {
	report("data/categories.json", validateCategory(c, i));
});

const slugs = new Set(categories.map((c) => c.slug));
if (slugs.size !== categories.length) {
	report("data/categories.json", [
		{ path: ".", message: "duplicate category slugs" },
	]);
}

// ---- products ----
const dir = join(DATA, "products");
const files = readdirSync(dir).filter((f) => f.endsWith(".json"));
const seen = new Set<string>();
const products: Product[] = [];

for (const file of files) {
	const value = readJson(join(dir, file));
	if (value === null) continue;
	const name = basename(file, ".json");
	const issues = validateProduct(value, name, slugs);
	if (seen.has(name))
		issues.push({ path: "slug", message: "duplicate product" });
	seen.add(name);
	report(`data/products/${file}`, issues);
	if (issues.length === 0) products.push(value as Product);
}

/* ---- archived repos -------------------------------------------------------
 *
 * `data/health.json` is generated by `bun run health` (weekly, via
 * .github/workflows/health.yml) and committed. Validation only ever reads the
 * one field that is a hard, forge-reported fact rather than a judgement:
 * `archived`.
 *
 * ONLY A POSITIVE `archived: true` FAILS. A repo with no entry in the file, or
 * an entry with no `archived` key, is silently fine — and that is not a
 * loophole, it is the only correct behaviour:
 *
 *   - a brand new PR's repo has never been swept, so it cannot be in the file;
 *   - GitLab's unauthenticated API does not report `archived` at all, and
 *     Savannah is not queried, so those readings legitimately omit it;
 *   - a fresh clone that has never run `bun run health` has no file.
 *
 * Treating any of those as "archived" would block PRs for the crime of being
 * new. Absence is not evidence.
 *
 * It is an error and not a warning. The warning already existed — `bun run
 * health` has printed archived repos all along — and grafana/oncall sat cited
 * as a live alternative for months regardless. A warning in a log that runs
 * weekly, unattended, is not a control. The fix is always cheap and always
 * available to whoever is blocked (repoint the entry, or drop it), and the
 * blast radius is bounded by the same rule above: it can only fire on a repo
 * somebody has already swept and the forge has already declared dead.
 */
const healthPath = join(DATA, "health.json");
if (existsSync(healthPath)) {
	const health = readJson(healthPath) as HealthFile | null;
	const repos = health?.repos ?? {};
	for (const p of products) {
		for (const [i, a] of p.alternatives.entries()) {
			if (a.kind !== "oss") continue;
			if (repos[healthKey(a.source)]?.archived !== true) continue;
			report(`data/products/${p.slug}.json`, [
				{
					path: `alternatives[${i}].source`,
					message: `${a.source.path} is archived upstream — replace it or drop it (reading from ${health?.fetchedAt ?? "an undated run"})`,
				},
			]);
		}
	}
}

// ---- summary ----
const byVerdict = (v: string) => products.filter((p) => p.verdict === v).length;
const altCount = products.reduce((n, p) => n + p.alternatives.length, 0);
const cheaper = products.filter((p) =>
	p.alternatives.some((a) => a.kind === "cheaper"),
).length;

console.log(
	`\n${files.length} products · ${categories.length} categories · ${altCount} alternatives`,
);
console.log(
	`  verdicts: ${byVerdict("yes")} replaceable, ${byVerdict("almost")} almost, ${byVerdict("not-yet")} not yet`,
);
console.log(`  ${cheaper} products also list a cheaper commercial option`);
for (const lang of SupportedLangs) {
	const n = products.filter((p) => productLangs(p).includes(lang)).length;
	const pct = files.length ? Math.round((n / files.length) * 100) : 0;
	console.log(`  ${lang}: ${n}/${files.length} fully translated (${pct}%)`);
}

if (failed > 0) {
	console.error(`\n${failed} problem(s). Nothing was written.`);
	process.exit(1);
}
console.log("\nAll good.");
