/**
 * Category marks.
 *
 * `data/categories.json` names a lucide icon per category, and until now nothing
 * rendered it. The names are imported one by one rather than through
 * `lucide-react/dynamic`: every page here is prerendered to static HTML, and a
 * dynamically imported icon would be absent from the document a crawler reads and
 * would arrive a frame late for everyone else. Explicit imports also tree-shake —
 * 78 marks, not the whole 1,500-icon set.
 *
 * Generated from the icon names in use. A category naming an icon that is not
 * here falls back to `Shapes` rather than rendering a hole, so adding a category
 * with a new icon is never a broken page — just an unstyled one until it is added.
 */

import type { LucideIcon } from "lucide-react";
import {
	Activity,
	Archive,
	BadgePercent,
	Box,
	Boxes,
	Brain,
	Calendar,
	CalendarCheck,
	ChartLine,
	CheckCheck,
	ClipboardList,
	Cloud,
	Contact,
	CreditCard,
	Database,
	DoorOpen,
	Factory,
	FileCode,
	FileText,
	FlaskConical,
	Gamepad2,
	GitBranch,
	Glasses,
	Globe,
	GraduationCap,
	Hammer,
	Handshake,
	HardDrive,
	HardHat,
	HeartHandshake,
	HeartPulse,
	House,
	Joystick,
	Kanban,
	KeyRound,
	Languages,
	Layers,
	LayoutTemplate,
	Library,
	LifeBuoy,
	Mail,
	// Aliased: a bare `Map` import shadows the global.
	Map as MapIcon,
	Megaphone,
	MessageSquare,
	Mic,
	Microscope,
	MonitorPlay,
	Network,
	NotebookPen,
	Package,
	Palette,
	PenTool,
	PiggyBank,
	RadioTower,
	Receipt,
	Scale,
	ScreenShare,
	Search,
	Server,
	Shapes,
	Shield,
	ShoppingBag,
	ShoppingCart,
	Sigma,
	Smartphone,
	Sparkles,
	Sprout,
	Store,
	Target,
	Terminal,
	TrendingUp,
	Truck,
	Tv,
	Users,
	Video,
	Webhook,
	Workflow,
	Wrench,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
	activity: Activity,
	archive: Archive,
	"badge-percent": BadgePercent,
	box: Box,
	boxes: Boxes,
	brain: Brain,
	calendar: Calendar,
	"calendar-check": CalendarCheck,
	"chart-line": ChartLine,
	"check-check": CheckCheck,
	"clipboard-list": ClipboardList,
	cloud: Cloud,
	contact: Contact,
	"credit-card": CreditCard,
	database: Database,
	"door-open": DoorOpen,
	factory: Factory,
	"file-code": FileCode,
	"file-text": FileText,
	"flask-conical": FlaskConical,
	"gamepad-2": Gamepad2,
	"git-branch": GitBranch,
	glasses: Glasses,
	globe: Globe,
	"graduation-cap": GraduationCap,
	hammer: Hammer,
	handshake: Handshake,
	"hard-drive": HardDrive,
	"hard-hat": HardHat,
	"heart-handshake": HeartHandshake,
	"heart-pulse": HeartPulse,
	house: House,
	joystick: Joystick,
	kanban: Kanban,
	"key-round": KeyRound,
	languages: Languages,
	layers: Layers,
	"layout-template": LayoutTemplate,
	library: Library,
	"life-buoy": LifeBuoy,
	mail: Mail,
	map: MapIcon,
	megaphone: Megaphone,
	"message-square": MessageSquare,
	mic: Mic,
	microscope: Microscope,
	"monitor-play": MonitorPlay,
	network: Network,
	"notebook-pen": NotebookPen,
	package: Package,
	palette: Palette,
	"pen-tool": PenTool,
	"piggy-bank": PiggyBank,
	"radio-tower": RadioTower,
	receipt: Receipt,
	scale: Scale,
	"screen-share": ScreenShare,
	search: Search,
	server: Server,
	shapes: Shapes,
	shield: Shield,
	"shopping-bag": ShoppingBag,
	"shopping-cart": ShoppingCart,
	sigma: Sigma,
	smartphone: Smartphone,
	sparkles: Sparkles,
	sprout: Sprout,
	store: Store,
	target: Target,
	terminal: Terminal,
	"trending-up": TrendingUp,
	truck: Truck,
	tv: Tv,
	users: Users,
	video: Video,
	webhook: Webhook,
	workflow: Workflow,
	wrench: Wrench,
};

export const categoryIcon = (name: string): LucideIcon => ICONS[name] ?? Shapes;
